import type { Service } from "./services";

/**
 * Social Media Management service entries.
 *
 * These extend the central service registry (consumed by the mega menu,
 * services hub, SEO schema and sitemap) so no page-specific wiring is needed.
 * Each entry is a full Service record and is written uniquely per service.
 */
export const socialServiceEntries: Service[] = [
  {
    slug: "social-media-management",
    name: "Social Media Management",
    shortName: "Social Media Management",
    icon: "Share2",
    tagline: "Consistent presence, real engagement",
    shortDesc:
      "Complete social media management designed to build your brand presence, engagement and audience across major social platforms.",
    metaTitle: "Social Media Management Services",
    metaDescription:
      "Complete social media management designed to build your brand presence, engagement and audience across major social platforms with Webamazee.",
    keyword: "social media management",
    metaKeywords: ["social media management", "social media strategy", "social media content", "brand presence", "engagement growth"],
    hero: {
      eyebrow: "Social Media Management",
      title: "A social presence that",
      highlight: "builds your brand",
      subtitle:
        "We plan, create, publish and manage your social media so your brand stays consistent, active and engaging across the platforms your customers use.",
      trust: ["Multi-platform coverage", "Content calendars", "Community engagement"],
    },
    pains: [
      { title: "Posting is sporadic", desc: "Without a plan, social accounts go quiet exactly when customers are checking you out." },
      { title: "No time for content", desc: "Running the business leaves little room to design posts, write captions and respond." },
      { title: "Inconsistent branding", desc: "Mixed visuals and tone make a business look unprofessional and hard to remember." },
      { title: "Engagement goes nowhere", desc: "Likes and comments are not being turned into followers, enquiries or reviews." },
    ],
    overview: [
      "Social media management is the ongoing work of making your brand present and useful on the platforms where your customers spend their time. We handle the full cycle: strategy, content creation, publishing, monitoring and engagement.",
      "Rather than posting randomly, we build a content calendar around your offers, audience and goals. Every post is designed to be on-brand, useful and aligned with your wider marketing, so social media supports enquiries rather than existing in a silo.",
      "The result is a consistent, professional presence that keeps your business visible, builds trust with your audience and creates clear paths from social posts to your website and contact options.",
    ],
    whoNeeds: [
      "Businesses that know they should be active on social media but lack the time",
      "Brands with inconsistent posting and no clear content strategy",
      "Companies wanting a professional, unified look across platforms",
      "Teams that want social media to support, not distract from, lead generation",
    ],
    examples: [
      "Plan content calendars around products, services and audience questions.",
      "Create consistent brand visuals and copy for the chosen platforms.",
      "Schedule publishing and define an approach to comments and enquiries.",
    ],
    whyMattersTitle: "Why consistent social management matters",
    whyMatters: [
      "Customers routinely check social profiles before they contact a business. An active, well-managed presence builds confidence; a neglected one quietly sends visitors away.",
      "Consistency compounds. Regular, on-brand content keeps you top of mind and gives the algorithm reasons to show your posts, while sporadic posting resets your momentum.",
      "Managed social media turns scattered effort into a measurable channel, connected to your website, campaigns and enquiry paths rather than operating as an afterthought.",
    ],
    process: [
      { step: "01", title: "Audit & strategy", desc: "We review your profiles, audience and competitors to set goals and positioning." },
      { step: "02", title: "Content planning", desc: "We build a monthly calendar of posts around your offers and audience needs." },
      { step: "03", title: "Create & design", desc: "We produce on-brand visuals, captions and formats for each platform." },
      { step: "04", title: "Publish & schedule", desc: "We post at optimal times and maintain a steady, consistent cadence." },
      { step: "05", title: "Engage", desc: "We monitor comments and messages and keep conversations responsive." },
      { step: "06", title: "Report & refine", desc: "We review performance each month and refine what drives results." },
    ],
    included: [
      { icon: "Share2", title: "Multi-platform management", desc: "Coordinated presence across Instagram, Facebook, LinkedIn and more." },
      { icon: "CalendarClock", title: "Content calendar", desc: "A planned monthly schedule so posting stays consistent." },
      { icon: "PenTool", title: "Content creation", desc: "On-brand graphics, captions and formats designed for each network." },
      { icon: "MessageCircle", title: "Community engagement", desc: "Monitoring and responding to comments and messages." },
      { icon: "PieChart", title: "Monthly reporting", desc: "Clear reporting on growth, reach and engagement." },
      { icon: "Radar", title: "Profile optimisation", desc: "Polished bios, branding and links that guide people to action." },
    ],
    whyChoose: [
      { icon: "Sparkles", title: "Strategy-led", desc: "Posts support real business goals, not just vanity activity." },
      { icon: "BadgeCheck", title: "Brand consistent", desc: "Every asset matches your identity and tone of voice." },
      { icon: "Users", title: "Audience focused", desc: "Content built around what your customers actually care about." },
      { icon: "BarChart3", title: "Transparent", desc: "Clear monthly reporting with no hidden metrics." },
      { icon: "Gauge", title: "Connected", desc: "Social activity links into your website and campaigns." },
      { icon: "Globe", title: "International", desc: "Built for businesses across the US, UK, Australia and beyond." },
    ],
    industries: ["Retail", "Hospitality", "Healthcare", "Professional Services", "E-Commerce", "Real Estate"],
    techStack: ["Meta Business Suite", "Canva", "Buffer", "Hootsuite", "Later", "Google Analytics"],
    measurementAreas: [
      "Publishing consistency",
      "Content engagement",
      "Community response",
      "Website and enquiry referrals",
    ],
    faqs: [
      { q: "Which platforms do you manage?", a: "We commonly manage Instagram, Facebook and LinkedIn, and can include others based on where your audience is active." },
      { q: "Do you create the content too?", a: "Yes. Content planning, design, captions and scheduling are part of management, not an add-on." },
      { q: "How often will you post?", a: "Cadence depends on your plan and audience; we agree a realistic, consistent schedule rather than posting unpredictably." },
      { q: "Will the content match my brand?", a: "Absolutely. We build around your visual identity, tone and messaging so everything stays recognisable." },
      { q: "Do you respond to comments and messages?", a: "We monitor and engage with comments and messages, and flag anything needing your direct input." },
      { q: "Can this work alongside ads or SEO?", a: "Yes. Management pairs naturally with paid social campaigns and SEO, and we keep them coordinated." },
    ],
    related: [
      "social-media-marketing",
      "instagram-marketing",
      "facebook-marketing",
      "linkedin-marketing",
      "social-media-advertising",
    ],
  },
  {
    slug: "social-media-marketing",
    name: "Social Media Marketing",
    shortName: "Social Media Marketing",
    icon: "Megaphone",
    tagline: "Reach, engagement and growth",
    shortDesc:
      "Strategic social media marketing campaigns designed to increase reach, engagement and business growth.",
    metaTitle: "Social Media Marketing Services",
    metaDescription:
      "Strategic social media marketing campaigns designed to increase reach, engagement and business growth with Webamazee's data-led approach.",
    keyword: "social media marketing",
    metaKeywords: ["social media marketing", "social media campaigns", "social media strategy", "social media growth", "social media ROI"],
    hero: {
      eyebrow: "Social Media Marketing",
      title: "Turn social feeds into",
      highlight: "business growth",
      subtitle:
        "We build goal-driven social media marketing campaigns that grow your reach and engagement and connect attention to real business outcomes.",
      trust: ["Campaign strategy", "Audience targeting", "Growth reporting"],
    },
    pains: [
      { title: "Posts get little reach", desc: "Without strategy, content reaches a tiny fraction of even your own followers." },
      { title: "Engagement doesn't convert", desc: "Likes look nice but never translate to clicks, signups or sales." },
      { title: "No clear strategy", desc: "Random posts without audience insight or goals waste time and budget." },
      { title: "Hard to prove value", desc: "Without tracking, it is impossible to see what social media actually delivers." },
    ],
    overview: [
      "Social media marketing turns your presence into a structured growth channel. We define the audience, message and content approach, then run campaigns designed around a specific goal such as awareness, engagement, traffic or leads.",
      "We combine organic content with targeted promotion where it makes sense, using platform analytics to understand what resonates and doubling down on the angles that perform. Every campaign is tied to a measurable outcome rather than vanity metrics.",
      "The result is coordinated marketing that grows meaningful reach and engagement and sends interested people toward your website, offers and contact paths.",
    ],
    whoNeeds: [
      "Businesses that want to grow beyond their current follower base",
      "Brands launching offers, products or campaigns",
      "Companies whose social activity is not tied to revenue goals",
      "Teams that want data-driven social campaigns rather than guesswork",
    ],
    examples: [
      "Set campaign goals and choose the audience and content to match.",
      "Test creative and messages with tracking configured before launch.",
      "Connect social activity to relevant website or enquiry actions.",
    ],
    whyMattersTitle: "Why social marketing needs strategy",
    whyMatters: [
      "Social platforms reward content that generates meaningful engagement. A strategic approach produces that engagement deliberately instead of hoping a post happens to perform.",
      "Attention without direction is wasted. We connect each campaign to a goal and a next step, so increased reach and engagement actually feed your funnel.",
      "Data-driven marketing improves over time. By testing angles, formats and audiences, campaigns compound instead of resetting with every new post.",
    ],
    process: [
      { step: "01", title: "Goal & audience", desc: "We define the campaign goal and the audience it needs to reach." },
      { step: "02", title: "Content strategy", desc: "We plan themes, formats and messaging built around that audience." },
      { step: "03", title: "Campaign build", desc: "We create assets and set up organic and promoted activity." },
      { step: "04", title: "Launch", desc: "We publish and distribute across the right platforms." },
      { step: "05", title: "Optimise", desc: "We test and refine based on real performance data." },
      { step: "06", title: "Report", desc: "We report on reach, engagement and business outcomes." },
    ],
    included: [
      { icon: "Crosshair", title: "Audience targeting", desc: "Campaigns built around relevant audiences and their interests." },
      { icon: "PenTool", title: "Campaign content", desc: "Creative and copy designed around a clear objective." },
      { icon: "TrendingUp", title: "Reach & engagement growth", desc: "Activity optimised to expand meaningful visibility." },
      { icon: "Radar", title: "Performance testing", desc: "Testing angles and formats to find what works." },
      { icon: "PieChart", title: "Growth reporting", desc: "Reporting tied to goals, not just vanity metrics." },
      { icon: "Send", title: "Funnel connection", desc: "Paths from social content to your site and offers." },
    ],
    whyChoose: [
      { icon: "Target", title: "Goal driven", desc: "Every campaign starts with a defined business outcome." },
      { icon: "BarChart3", title: "Data led", desc: "Decisions come from analytics and testing." },
      { icon: "Sparkles", title: "Creative", desc: "Content designed to stop the scroll and feel on-brand." },
      { icon: "Gauge", title: "Performance focused", desc: "We optimise for results, not just follower counts." },
      { icon: "Users", title: "Audience first", desc: "Messaging shaped around real customer intent." },
      { icon: "Globe", title: "International", desc: "Experienced across multiple markets and platforms." },
    ],
    industries: ["E-Commerce", "SaaS", "Retail", "Hospitality", "Education", "Professional Services"],
    techStack: ["Meta Ads Manager", "LinkedIn Campaign Manager", "Google Analytics", "Canva", "Buffer", "Hotjar"],
    measurementAreas: [
      "Audience reach",
      "Engagement quality",
      "Campaign attribution",
      "Enquiry activity",
    ],
    faqs: [
      { q: "How is this different from social media management?", a: "Management keeps your presence active and on-brand; marketing adds goal-driven campaigns and promotion designed to grow reach, engagement and conversions." },
      { q: "Does this include paid ads?", a: "It can. We build organic campaigns and can coordinate paid promotion, with dedicated social advertising available as a focused service." },
      { q: "How do you measure success?", a: "We define goals up front and report on metrics tied to them, such as reach, engagement, traffic and leads, rather than likes alone." },
      { q: "Which platforms work best?", a: "It depends on your audience. We focus on the platforms where your customers are genuinely active." },
      { q: "How soon will I see results?", a: "Timing varies by audience, platform, content and campaign. We review performance trends and adjust the approach." },
      { q: "Can you work with an existing team?", a: "Yes. We can run campaigns end-to-end or complement your in-house content and design resources." },
    ],
    related: ["social-media-management", "social-media-advertising", "instagram-marketing"],
  },
  {
    slug: "instagram-marketing",
    name: "Instagram Marketing",
    shortName: "Instagram Marketing",
    icon: "Instagram",
    tagline: "Grow an audience that engages",
    shortDesc:
      "Instagram-focused strategies, content and campaigns designed to grow your audience and generate meaningful engagement.",
    metaTitle: "Instagram Marketing & Growth Services",
    metaDescription:
      "Instagram-focused strategies, content and campaigns designed to grow your audience and generate meaningful engagement with Webamazee.",
    keyword: "Instagram marketing",
    metaKeywords: ["Instagram marketing", "Instagram growth", "Instagram content strategy", "Instagram engagement", "Instagram advertising"],
    hero: {
      eyebrow: "Instagram Marketing",
      title: "Grow an Instagram that",
      highlight: "people engage with",
      subtitle:
        "We build Instagram strategies, content and campaigns that grow a relevant audience and turn visual storytelling into real engagement and enquiries.",
      trust: ["Content strategy", "Reels & stories", "Audience growth"],
    },
    pains: [
      { title: "Followers don't engage", desc: "A large follower count means little when posts get few comments, saves or shares." },
      { title: "Content feels generic", desc: "Stock-feeling posts and inconsistent aesthetics fail to build a recognisable brand." },
      { title: "Reels are intimidating", desc: "Short-form video drives reach but many businesses don't know where to start." },
      { title: "No path to purchase", desc: "Engaging posts rarely guide viewers toward the website, offers or messages." },
    ],
    overview: [
      "Instagram marketing is about building a visual presence that attracts the right audience and encourages genuine interaction. We develop a content strategy tailored to how the platform works, covering feed posts, reels, stories and profile optimisation.",
      "We focus on content that fits your brand and your customers, from educational and behind-the-scenes posts to offers and community-building formats, and we use Instagram's own insights to refine what resonates.",
      "The result is an Instagram presence that grows a relevant audience, sustains engagement and makes it easy for interested followers to take the next step.",
    ],
    whoNeeds: [
      "Visual, consumer-facing brands that thrive on imagery and video",
      "Retailers, cafes, salons, studios and lifestyle businesses",
      "Brands wanting to use reels and stories effectively",
      "Businesses whose Instagram looks inactive or unprofessional",
    ],
    examples: [
      "Organise a profile so visitors quickly understand the offer.",
      "Plan a mix of feed posts, Reels and Stories around campaign goals.",
      "Use clear profile links and calls to action for enquiries.",
    ],
    whyMattersTitle: "Why Instagram rewards focused effort",
    whyMatters: [
      "Instagram strongly favours engaging, visual and especially short-form video content. A deliberate strategy captures that reach instead of posting into the void.",
      "A strong, consistent aesthetic builds recognition and trust, making followers more likely to remember and choose your business.",
      "Engagement is the bridge between attention and action. Content designed to encourage saves, shares and messages creates a path from a post to a customer.",
    ],
    process: [
      { step: "01", title: "Profile & audit", desc: "We optimise your profile and review current content and competitors." },
      { step: "02", title: "Content strategy", desc: "We define themes, pillars and a visual direction for your brand." },
      { step: "03", title: "Create", desc: "We produce feed posts, reels, stories and captions." },
      { step: "04", title: "Publish", desc: "We schedule content at the best times for your audience." },
      { step: "05", title: "Engage", desc: "We encourage and respond to comments, saves and messages." },
      { step: "06", title: "Refine", desc: "We use insights to double down on high-performing content." },
    ],
    included: [
      { icon: "Instagram", title: "Profile optimisation", desc: "A polished bio, highlights and links that convert visitors." },
      { icon: "Video", title: "Reels strategy", desc: "Short-form video planned around reach and engagement." },
      { icon: "Image", title: "Feed & story content", desc: "Consistent, on-brand visuals and captions." },
      { icon: "Hash", title: "Hashtag & caption strategy", desc: "Discoverability built into every post." },
      { icon: "Heart", title: "Engagement growth", desc: "Content designed for comments, saves and shares." },
      { icon: "PieChart", title: "Performance insights", desc: "Reporting on growth and what resonates." },
    ],
    whyChoose: [
      { icon: "Sparkles", title: "Native to Instagram", desc: "Strategy built around how the platform actually performs." },
      { icon: "BadgeCheck", title: "Strong visuals", desc: "A cohesive, recognisable aesthetic for your brand." },
      { icon: "Video", title: "Reels confident", desc: "Short-form video handled without guesswork." },
      { icon: "Heart", title: "Engagement focused", desc: "We optimise for genuine interaction, not just followers." },
      { icon: "Gauge", title: "Insight driven", desc: "Decisions guided by real Instagram analytics." },
      { icon: "Globe", title: "International", desc: "Experienced building brands across markets." },
    ],
    industries: ["Fashion", "Beauty", "Food & Beverage", "Fitness", "Travel", "Retail"],
    techStack: ["Instagram", "Meta Business Suite", "Canva", "CapCut", "Later", "Google Analytics"],
    measurementAreas: [
      "Profile actions",
      "Content engagement",
      "Audience response",
      "Enquiry activity",
    ],
    faqs: [
      { q: "Do you create reels for us?", a: "Yes. Reels and short-form video are a core part of the strategy where they fit your audience and goals." },
      { q: "How often will you post?", a: "We agree a realistic cadence based on your plan, balancing feed posts, reels and stories consistently." },
      { q: "Will it match my brand look?", a: "Yes. We build a cohesive visual direction so your grid and stories feel unmistakably yours." },
      { q: "Can you help grow followers?", a: "We focus on growing a relevant, engaged audience rather than buying followers, which does not help your business." },
      { q: "Do you handle comments and DMs?", a: "We monitor engagement and messages and coordinate with you on anything needing a personal response." },
      { q: "Does Instagram work for B2B?", a: "It depends on the audience. For more professional audiences we often pair Instagram with LinkedIn marketing." },
    ],
    related: ["social-media-management", "social-media-marketing", "facebook-marketing"],
  },
  {
    slug: "facebook-marketing",
    name: "Facebook Marketing",
    shortName: "Facebook Marketing",
    icon: "Facebook",
    tagline: "Reach local audiences and generate leads",
    shortDesc:
      "Facebook marketing strategies that help businesses reach their target audience and generate leads.",
    metaTitle: "Facebook Marketing & Ads Services",
    metaDescription:
      "Facebook marketing strategies that help businesses reach their target audience and generate leads with Webamazee's targeted approach.",
    keyword: "Facebook marketing",
    metaKeywords: ["Facebook marketing", "Facebook ads", "Meta advertising", "Facebook lead generation", "social media advertising"],
    hero: {
      eyebrow: "Facebook Marketing",
      title: "Reach the right audience and",
      highlight: "generate leads",
      subtitle:
        "We build Facebook marketing strategies and campaigns that reach your target audience, build local awareness and turn attention into leads.",
      trust: ["Audience targeting", "Local awareness", "Lead campaigns"],
    },
    pains: [
      { title: "Posts don't reach anyone", desc: "Organic reach alone rarely puts your message in front of new customers." },
      { title: "Wrong audience", desc: "Content is seen by people who will never buy rather than local, relevant buyers." },
      { title: "No lead capture", desc: "Campaigns generate interest but no practical way to capture and follow up." },
      { title: "Budget is wasted", desc: "Boosting posts without targeting spends money on audiences that don't convert." },
    ],
    overview: [
      "Facebook marketing combines page presence, targeted content and campaigns for audiences relevant to your offer. We define targeting around location, interests and behaviour, then build content and promotions around clear lead goals.",
      "For local businesses, Facebook remains a powerful way to stay visible within a community; for broader offers, its targeting supports precise reach. We set up practical lead capture and follow-up paths so interest does not evaporate.",
      "The result is campaigns that reach the right audience, build useful awareness and generate enquiries you can actually act on.",
    ],
    whoNeeds: [
      "Local businesses serving a specific area or community",
      "Brands that want to generate enquiries or bookings",
      "Companies boosting posts without a clear targeting strategy",
      "Businesses with offers suited to broad, interest-based audiences",
    ],
    examples: [
      "Build campaigns around specific service areas and audiences.",
      "Pair audience targeting with a clear lead-capture journey.",
      "Review creative and delivery using available campaign reporting.",
    ],
    whyMattersTitle: "Why Facebook still drives local leads",
    whyMatters: [
      "Facebook offers local and interest-based targeting options. We shape campaigns around your audience, offer and available budget.",
      "Awareness only has value when it connects to a next step. We build lead capture and follow-up into campaigns from the start.",
      "Without strategy, boosting posts wastes budget. Targeted, goal-driven campaigns make spend accountable and improvable over time.",
    ],
    process: [
      { step: "01", title: "Audience definition", desc: "We identify the locations, interests and behaviours that matter." },
      { step: "02", title: "Page & presence", desc: "We ensure your page and content support a professional impression." },
      { step: "03", title: "Campaign strategy", desc: "We plan content and promotions around lead or awareness goals." },
      { step: "04", title: "Targeting setup", desc: "We configure precise audiences and placements." },
      { step: "05", title: "Lead capture", desc: "We set up forms, messages or landing paths to capture interest." },
      { step: "06", title: "Optimise & report", desc: "We refine targeting and report on leads and reach." },
    ],
    included: [
      { icon: "Facebook", title: "Page strategy", desc: "A professional, active presence that supports campaigns." },
      { icon: "Crosshair", title: "Audience targeting", desc: "Location, interest and behaviour-based reach." },
      { icon: "Megaphone", title: "Campaign content", desc: "Posts and creative built around campaign goals." },
      { icon: "UserPlus", title: "Lead generation", desc: "Forms and messaging paths to capture enquiries." },
      { icon: "MapPin", title: "Local awareness", desc: "Reach within the communities you serve." },
      { icon: "PieChart", title: "Performance reporting", desc: "Clear reporting on reach, leads and cost." },
    ],
    whyChoose: [
      { icon: "Target", title: "Precise targeting", desc: "Budget aimed at audiences likely to convert." },
      { icon: "UserPlus", title: "Lead focused", desc: "Campaigns built to capture and follow up enquiries." },
      { icon: "MapPin", title: "Local expertise", desc: "Strong support for community and area-based reach." },
      { icon: "BarChart3", title: "Accountable spend", desc: "Transparent reporting on what budget delivers." },
      { icon: "BadgeCheck", title: "Professional content", desc: "On-brand creative that builds trust." },
      { icon: "Globe", title: "International", desc: "Capable across local and international markets." },
    ],
    industries: ["Local Services", "Real Estate", "Healthcare", "Retail", "Automotive", "Home Services"],
    techStack: ["Meta Ads Manager", "Meta Business Suite", "Facebook", "Google Analytics", "Canva", "Zapier"],
    measurementAreas: [
      "Audience relevance",
      "Lead capture",
      "Campaign attribution",
      "Local engagement",
    ],
    faqs: [
      { q: "Is Facebook still worth using for marketing?", a: "Yes, especially for local and interest-based targeting and for businesses that want to generate practical leads." },
      { q: "Does this include paid ads?", a: "Facebook marketing includes targeted campaigns; for fully managed paid spend across networks, see our social media advertising service." },
      { q: "How do you capture leads?", a: "We use lead forms, messaging or dedicated landing paths and ensure there is a clear follow-up process." },
      { q: "Can you target a specific local area?", a: "Yes. Location targeting is a core strength and is ideal for businesses serving a defined region." },
      { q: "What budget do I need?", a: "Budgets vary; we recommend a level that allows meaningful testing and will advise realistic figures for your goals." },
      { q: "How do you report results?", a: "We report on reach, engagement and, most importantly, leads and cost per outcome rather than impressions alone." },
    ],
    related: ["social-media-management", "social-media-marketing", "social-media-advertising"],
  },
  {
    slug: "linkedin-marketing",
    name: "LinkedIn Marketing",
    shortName: "LinkedIn Marketing",
    icon: "Linkedin",
    tagline: "B2B visibility, authority and leads",
    shortDesc:
      "Professional LinkedIn marketing strategies for B2B visibility, authority and lead generation.",
    metaTitle: "LinkedIn Marketing & B2B Growth Services",
    metaDescription:
      "Professional LinkedIn marketing strategies for B2B visibility, authority and lead generation with Webamazee.",
    keyword: "LinkedIn marketing",
    metaKeywords: ["LinkedIn marketing", "B2B lead generation", "LinkedIn content strategy", "LinkedIn visibility", "B2B social media"],
    hero: {
      eyebrow: "LinkedIn Marketing",
      title: "Build B2B authority and",
      highlight: "generate leads",
      subtitle:
        "We help B2B businesses use LinkedIn to build professional visibility, demonstrate authority and connect with decision-makers who matter.",
      trust: ["B2B positioning", "Thought leadership", "Lead generation"],
    },
    pains: [
      { title: "Decision-makers don't know you", desc: "B2B buyers research vendors on LinkedIn before they ever reply to an outreach message." },
      { title: "Profiles look unfinished", desc: "Personal and company profiles that read like CVs fail to build commercial trust." },
      { title: "Content has no authority", desc: "Posting promotions instead of useful insight means prospects scroll past." },
      { title: "Networking isn't converting", desc: "Connections sit idle with no structured way to build relationships or leads." },
    ],
    overview: [
      "LinkedIn can support B2B visibility and professional relationships. We build a presence across company and relevant personal profiles, positioning your business around the expertise your buyers care about.",
      "We develop thought-leadership content, optimise profiles for credibility and run focused outreach and engagement that builds relationships with decision-makers rather than spraying connection requests.",
      "The result is a credible, authoritative LinkedIn presence that keeps your business visible to the right professionals and creates structured opportunities for conversations and leads.",
    ],
    whoNeeds: [
      "B2B companies selling to professional or enterprise buyers",
      "Consultancies, agencies and professional services firms",
      "Founders and sales leaders who want a stronger personal brand",
      "Businesses whose LinkedIn presence is inactive or purely promotional",
    ],
    examples: [
      "Clarify company and founder positioning for the people you want to reach.",
      "Plan expert-led content that shows how you work.",
      "Create a considered path from useful posts to business conversations.",
    ],
    whyMattersTitle: "Why LinkedIn matters for B2B growth",
    whyMatters: [
      "Buyers and decision-makers use LinkedIn to evaluate vendors and people. A credible, active presence directly influences whether they take you seriously.",
      "Authority compounds. Publishing useful insight positions your team as experts and makes outreach far more effective when you initiate conversations.",
      "Structured LinkedIn activity creates a repeatable B2B pipeline, turning a static network into a channel for relationships and leads.",
    ],
    process: [
      { step: "01", title: "Positioning", desc: "We define how your business and leaders should be perceived." },
      { step: "02", title: "Profile optimisation", desc: "We refine company and personal profiles for credibility." },
      { step: "03", title: "Content strategy", desc: "We plan thought-leadership posts around buyer concerns." },
      { step: "04", title: "Publishing", desc: "We create and post consistent, professional content." },
      { step: "05", title: "Engagement & outreach", desc: "We build relationships with the right decision-makers." },
      { step: "06", title: "Measure", desc: "We track visibility, relationships and lead opportunities." },
    ],
    included: [
      { icon: "Linkedin", title: "Profile optimisation", desc: "Company and personal profiles built for credibility." },
      { icon: "FileText", title: "Thought-leadership content", desc: "Insight-led posts that demonstrate expertise." },
      { icon: "Users", title: "Audience building", desc: "Connecting with relevant decision-makers and peers." },
      { icon: "MessageCircle", title: "Strategic engagement", desc: "Structured interaction that builds relationships." },
      { icon: "UserPlus", title: "B2B lead generation", desc: "Paths from visibility to conversations and calls." },
      { icon: "PieChart", title: "Performance reporting", desc: "Reporting on reach, engagement and opportunities." },
    ],
    whyChoose: [
      { icon: "BadgeCheck", title: "B2B specialist", desc: "Strategy built for professional buyers, not consumers." },
      { icon: "Sparkles", title: "Authority building", desc: "Content that positions your team as experts." },
      { icon: "Users", title: "Relationship led", desc: "We focus on real connections rather than spammy outreach." },
      { icon: "FileText", title: "Credible content", desc: "Professional insight that earns trust." },
      { icon: "Gauge", title: "Pipeline focused", desc: "Activity measured against lead opportunities." },
      { icon: "Globe", title: "International", desc: "Experienced connecting across global markets." },
    ],
    industries: ["B2B SaaS", "Consulting", "Professional Services", "Technology", "Finance", "Recruitment"],
    techStack: ["LinkedIn", "LinkedIn Sales Navigator", "Google Docs", "Canva", "HubSpot", "Google Analytics"],
    measurementAreas: [
      "Profile engagement",
      "Content interactions",
      "Qualified conversations",
      "Website referral activity",
    ],
    faqs: [
      { q: "Do you work on personal profiles or company pages?", a: "Both. A business can use credible company pages and relevant personal profiles to share expertise and build professional relationships." },
      { q: "Is LinkedIn marketing just sending connection requests?", a: "No. Effective LinkedIn work combines positioning, authority content and genuine relationship building, not mass outreach." },
      { q: "How quickly does it generate leads?", a: "Authority and relationships take time, but a consistent approach creates a growing pipeline rather than one-off messages." },
      { q: "Do you write the posts?", a: "Yes. We develop thought-leadership content, with your input kept accurate to your expertise." },
      { q: "Is LinkedIn advertising included?", a: "Paid LinkedIn campaigns can be coordinated through our social media advertising service." },
      { q: "Does this suit small businesses?", a: "If you sell to other businesses or professionals, a focused LinkedIn presence is well worth building." },
    ],
    related: ["social-media-management", "social-media-marketing", "social-media-advertising"],
  },
  {
    slug: "social-media-advertising",
    name: "Social Media Advertising",
    shortName: "Social Media Advertising",
    icon: "Radar",
    tagline: "Paid campaigns that perform",
    shortDesc:
      "Paid social media campaigns designed to reach the right audience and maximize advertising performance.",
    metaTitle: "Social Media Advertising & Paid Social Services",
    metaDescription:
      "Paid social media campaigns designed to reach the right audience and maximize advertising performance with Webamazee.",
    keyword: "social media advertising",
    metaKeywords: ["social media advertising", "paid social campaigns", "paid social strategy", "social media ads", "audience targeting"],
    hero: {
      eyebrow: "Social Media Advertising",
      title: "Paid social that reaches",
      highlight: "the right people",
      subtitle:
        "We plan, build and manage paid social campaigns across platforms to reach your best audience and maximise the return on your advertising spend.",
      trust: ["Paid campaign setup", "Audience & retargeting", "Conversion tracking"],
    },
    pains: [
      { title: "Ad spend underperforms", desc: "Campaigns spend budget without clear return because targeting or creative is off." },
      { title: "No conversion tracking", desc: "It is impossible to optimise when you cannot see which ads drive real actions." },
      { title: "Audiences are too broad", desc: "Showing ads to everyone wastes money on people who will never convert." },
      { title: "Creative goes stale", desc: "The same ad fatigues audiences and results decay without ongoing testing." },
    ],
    overview: [
      "Social media advertising puts your message in front of precisely defined audiences on platforms like Facebook, Instagram and LinkedIn. We manage the full paid process: strategy, audience build, creative, tracking and ongoing optimisation.",
      "We start with the goal and the numbers that matter, such as leads, sales or signups, then set up proper conversion tracking so every decision is based on real performance. Campaigns are continuously tested and refined rather than set and forgotten.",
      "The result is accountable advertising spend that reaches the right people, keeps creative fresh and improves return over time.",
    ],
    whoNeeds: [
      "Businesses running paid social campaigns with weak or unclear results",
      "Brands scaling offers, products or lead generation",
      "Companies without reliable conversion tracking",
      "Teams that want professionally managed, optimised ad spend",
    ],
    examples: [
      "Set up conversion events and reporting before scaling a campaign.",
      "Test audience and creative options against a defined objective.",
      "Use remarketing where consent, tracking and audience size allow.",
    ],
    whyMattersTitle: "Why paid social needs active management",
    whyMatters: [
      "Paid social is competitive and dynamic; campaigns that are launched and left alone quickly waste budget as audiences and costs shift.",
      "Tracking is the foundation of performance. Without reliable conversion data, optimisation is guesswork and improvements are impossible to prove.",
      "Continuous testing of audiences and creative compounds. Well-managed campaigns get more efficient over time instead of decaying.",
    ],
    process: [
      { step: "01", title: "Goal & tracking", desc: "We define targets and set up accurate conversion tracking." },
      { step: "02", title: "Audience strategy", desc: "We build targeting, retargeting and lookalike audiences." },
      { step: "03", title: "Creative & copy", desc: "We produce ad variants designed for each platform." },
      { step: "04", title: "Launch", desc: "We set up campaigns, budgets and placements correctly." },
      { step: "05", title: "Optimise", desc: "We test and scale what works and cut what doesn't." },
      { step: "06", title: "Report", desc: "We report clearly on spend, results and return." },
    ],
    included: [
      { icon: "Crosshair", title: "Audience targeting", desc: "Precise interest, behaviour and location targeting." },
      { icon: "Radar", title: "Retargeting", desc: "Re-engage people who showed interest on your site." },
      { icon: "BarChart3", title: "Conversion tracking", desc: "Accurate measurement of leads, sales and signups." },
      { icon: "PenTool", title: "Ad creative", desc: "On-brand ad variants built for performance." },
      { icon: "TrendingUp", title: "Bid & budget optimisation", desc: "Spend managed toward the best return." },
      { icon: "PieChart", title: "Performance reporting", desc: "Transparent reporting on cost and outcomes." },
    ],
    whyChoose: [
      { icon: "Target", title: "Performance obsessed", desc: "We optimise toward real conversions and return." },
      { icon: "BarChart3", title: "Tracking first", desc: "Decisions rely on accurate conversion data." },
      { icon: "Sparkles", title: "Creative testing", desc: "Fresh, tested ads that resist fatigue." },
      { icon: "Gauge", title: "Actively managed", desc: "Ongoing optimisation, not set-and-forget." },
      { icon: "ShieldCheck", title: "Accountable spend", desc: "Clear reporting on every dollar of budget." },
      { icon: "Globe", title: "International", desc: "Campaigns managed across markets and platforms." },
    ],
    industries: ["E-Commerce", "SaaS", "Retail", "B2B Services", "Education", "Lead Generation"],
    techStack: ["Meta Ads Manager", "LinkedIn Campaign Manager", "Google Ads", "Google Tag Manager", "GA4", "Zapier"],
    measurementAreas: [
      "Conversion tracking",
      "Audience quality",
      "Creative performance",
      "Cost and return on ad spend",
    ],
    faqs: [
      { q: "Which platforms do you advertise on?", a: "We commonly manage Facebook, Instagram and LinkedIn ads, and can coordinate with Google advertising depending on goals." },
      { q: "Do I need a big budget?", a: "We recommend a budget large enough to gather meaningful data, and we will advise a realistic starting point for your goals." },
      { q: "How important is conversion tracking?", a: "Essential. We set up tracking first so every optimisation decision is based on real conversions." },
      { q: "How is this different from boosting a post?", a: "Boosting is a blunt tool; managed advertising uses structured targeting, retargeting, creative testing and tracking." },
      { q: "Do you create the ad creative?", a: "Yes. We produce and test ad copy and visuals aligned with your brand." },
      { q: "How do you report results?", a: "We report on spend, conversions, cost per result and return, clearly and regularly." },
    ],
    related: ["social-media-marketing", "social-media-management", "google-ranking-growth"],
  },
];
