import { withPage } from './browser.js';
import { getEmbeddedFontCss } from './fonts.js';
import { invoiceDocumentHtml, A4_PX } from '../../../shared/invoiceTemplate.js';

/** Loads the canonical invoice document into a page and waits for fonts. */
async function loadInvoicePage(page, invoice, mode) {
  const fontCss = await getEmbeddedFontCss();
  const html = invoiceDocumentHtml(invoice, { fontCss, mode });
  await page.setContent(html, { waitUntil: 'load', timeout: 30000 });
  await page.evaluate(() => document.fonts.ready);
  return html;
}

/**
 * Real, vector PDF generated by Chromium's print pipeline from the same
 * template the browser previews - not a screenshot. Long item lists reflow
 * onto additional A4 pages automatically.
 */
export async function renderInvoicePdf(invoice) {
  return withPage(async (page) => {
    await page.setViewport({ width: A4_PX.width, height: A4_PX.height, deviceScaleFactor: 1 });
    await loadInvoicePage(page, invoice, 'pdf');
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      preferCSSPageSize: true,
      displayHeaderFooter: false,
      margin: { top: '0', right: '0', bottom: '0', left: '0' },
    });
    return Buffer.from(pdf);
  });
}

/**
 * High-resolution image of the invoice only (2x DPR, white background,
 * no dashboard chrome).
 */
export async function renderInvoiceImage(invoice, { format = 'png', scale = 2 } = {}) {
  const type = format === 'jpg' || format === 'jpeg' ? 'jpeg' : 'png';
  const deviceScaleFactor = Math.min(Math.max(Number(scale) || 2, 1), 3);

  return withPage(async (page) => {
    await page.setViewport({ width: A4_PX.width, height: A4_PX.height, deviceScaleFactor });
    await loadInvoicePage(page, invoice, 'image');
    const element = await page.$('.wm-invoice');
    if (!element) throw new Error('Invoice element not found while rendering image');
    const buffer = await element.screenshot({
      type,
      ...(type === 'jpeg' ? { quality: 95 } : { omitBackground: false }),
      captureBeyondViewport: true,
    });
    return { buffer: Buffer.from(buffer), contentType: type === 'jpeg' ? 'image/jpeg' : 'image/png' };
  });
}
